name: Build

on:
  push:
    branches: [ofw]
  pull_request:
    branches: [ofw]

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: "ufbt: Build for dev channel"

    strategy:
      matrix:
        include:
          - name: dev channel
            sdk-channel: dev

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ofw
          sparse-checkout: findmy
      - name: Get commit message
        run: echo "COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        id: build-app
        with:
          # Set to 'release' to build for latest published release version
          sdk-channel: ${{ matrix.sdk-channel }}

      - name: Create Draft Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ env.COMMIT_MESSAGE }}
          release_name: Dev_Release ${{ env.COMMIT_MESSAGE }}
          draft: true
          prerelease: false
      
      - uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.build-app.outputs.fap-artifacts }}
          asset_name: ${{ github.event.repository.name }}.fap
          asset_content_type: application/fap

      - uses: eregon/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          release_id: ${{ steps.create_release.outputs.id }}