name: Build

on:
  push:
    branches: [ofw]
  pull_request:
    branches: [ofw]

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: "ufbt: Build for dev channel"

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ofw
          sparse-checkout: findmy

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        id: build-app
        with:
          # Set to 'release' to build for latest published release version
          sdk-channel: dev
          app-dir: findmy

      - name: Github Release
        uses: elgohr/Github-Release-Action@20231116201936
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          title: Latest Dev Release

      