name: Build

on:
  push:
    branches: [ofw]
  pull_request:
    branches: [ofw]

jobs:
  ufbt-build-action:
    runs-on: ubuntu-latest
    name: "ufbt: Build for dev channel"

    strategy:
      matrix:
        include:
          - name: dev channel
            sdk-channel: dev

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ofw
          sparse-checkout: findmy

      - name: Get commit message
        run: echo "COMMIT_MESSAGE=$(git log --format=%B -n 1 ${{ github.event.after }})" >> $GITHUB_ENV

      - name: Build with ufbt
        uses: flipperdevices/flipperzero-ufbt-action@v0.1.2
        id: build-app
        with:
          # Set to 'release' to build for latest published release version
          sdk-channel: ${{ matrix.sdk-channel }}
          app-dir: findmy
      
      - name: Get Release file
        run: echo "faf-artifacts=$(ls ${{ steps.build-app.outputs.fap-artifacts }})"
      
      - name: Create Release
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          path: ${{ steps.build-app.outputs.fap-artifacts }}